### Задание 1.

Как относятся друг к другу множество и
последовательность? (в ответе использовать
слова типа: часть, целое, общее, частное,
родитель, дочерний субъект и т.д.)

последовательность - это такой набор элементов (часть) множетсва, что для каждого его элемента можно назвать номер, предыдущий и следующий эемент. То есть последовательность - это результат последовательного выбора элементов из некоторого заданного множества.

### Задание 2
Прочитать высказывания
математической логики,
построить их отрицания и
*установить истинность.

$ \forall y \in [0;1]:sng(y)=1 $ для любого y, принадлежащего отрезку от 0 до 1, сигнум от y равен 1. _истина_

_отрицание_: $ \exists y \in [0;1]:sng(y)\neq 1 $ 

$ \forall n \in \mathbb{N} >2:\exists x,y,z \in \mathbb{N}: x^n=y^n+z^n$ для любого натурального n строго больше 2 существуют такие натуральные $ x,y,z $, для которых выполняется равенство $ x^n=y^n+z^n $ _истина_

_отрицание_: $ \exists n \in \mathbb{N} \leqslant 2:\forall x,y,z \in \mathbb{N}: x^n\neq y^n+z^n $


$ \forall x \in \mathbb{R} \exists X \in \mathbb{R}:X>x $ для любых рациональных $x$ существует такое рациональное $X$, что $X$ строго больше $x$ _истина_

_отрицание_: $\exists x \in \mathbb{R} \forall X \in \mathbb{R}:X\leqslant x$

$\forall x \in \mathbb{C} \nexists y \in \mathbb{C}:x>y \| x<y$ для любого комплексного $x$ не существует такое комплексное $y$ чтобы выполнялось неравенство $x<y$ или $y>x$ _истина_

_отрицание_: $\exists x \in \mathbb{C} \exists y \in \mathbb{C}:x\leqslant y \& x\geqslant y $

$\forall y \in [0; \pi / 2] \exists \varepsilon > 0 : \sin y < \sin(y + \varepsilon)$ для любого $y$, принадлежащего отрезку $[0; \pi / 2]$, существует такое строго положительное $\varepsilon$, для которого верно неравенство $\sin y < \sin(y + \varepsilon)$ _ложь_

_отрицание_: $\exists y \in [0; \pi / 2] \forall \varepsilon \leqslant 0 : \sin y \geqslant \sin(y + \varepsilon)$

$\forall y \in [0; \pi) \exists \varepsilon > 0 : \cos y > \cos(y + \varepsilon)$ для любого $y$, принадлежащего интервалу от 0 включительно до $\pi$ не включительно, существует строго положительное $\varepsilon$, при котором верно неравенство $\cos y > \cos(y + \varepsilon)$ _истина_

_отрицание_: $\exists y \in [0; \pi) \forall \varepsilon \leqslant 0 : \cos y \geqslant \cos(y + \varepsilon)$



$\exists x: x \notin \{\mathbb{N,Z,Q,R,C}\} $ существуют такие $x$, которые не принадлежат множествам натуральный, целых, рациональных, действительных и иррациональных чисел. _ложь_

_отрицание_: $\forall x: x \in \{\mathbb{N,Z,Q,R,C}\}$

### Задание 3
1. Даны три множества a,b и с. Необходимо выполнить все изученные виды
бинарных операций над всеми комбинациями множеств.
2. *Выполнить задание 1 на языке Python

In [24]:
import numpy as np
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([3,3,3])

In [23]:
print(f'пересечение a & b = {a&b}')
print(f'объединение a | b = {a|b}')
print(f'разность a - b = {a-b}')
print(f'симметрическая разность a ^ b = {a^b}')
print(f'декартого произведение a x b= {[[a0, b0] for a0 in a for b0 in b]}')

пересечение a & b = [0 2 2]
объединение a | b = [3 2 3]
разность a - b = [-1  0  1]
симметрическая разность a ^ b = [3 0 1]
декартого произведение a x b= [[1, 2], [1, 2], [1, 2], [2, 2], [2, 2], [2, 2], [3, 2], [3, 2], [3, 2]]


выполнить все комбинации бинарных операций для 3 списков - это как-то слишко много и долго. поэтому сделаю некоторые комбинации операций для a, b, с, без изменениях их порядка следования:

In [27]:
print(f'{a&b&c}')
print(f'{a&b|c}')
print(f'{a&b-c}')
print(f'{a&b^c}')

print(f'{a|b&c}')
print(f'{a|b|c}')
print(f'{a|b-c}')
print(f'{a|b^c}')

print(f'{a-b&c}')
print(f'{a-b|c}')
print(f'{a-b^c}')
print(f'{a-b-c}')

print(f'{a^b&c}')
print(f'{a^b|c}')
print(f'{a^b^c}')
print(f'{a^b-c}')

[0 2 2]
[3 3 3]
[1 2 3]
[3 1 1]
[3 2 3]
[3 3 3]
[-1 -1 -1]
[1 3 3]
[3 0 1]
[-1  3  3]
[-4  3  2]
[-4 -3 -2]
[3 0 1]
[3 3 3]
[0 3 2]
[-2 -3 -4]


### Задание 4
Даны 4 последовательности.
Необходимо:
1) исследовать их на
монотонность;
2) исследовать на
ограниченность;
3) найти пятый по счету член.

$\{a_n\}_{n=1}^\infty = 2^n-n$

1) последовательность монотонная, если знак разности между предыдущем и текущем ее членом не меняется.
$a_n - a_{n-1}=2^n-n-2^{n-1}-n+1=2^n-2^{n-1}-2\cdot n +1$ - это функция положительна для всех $n>0$, значит исходная последовательность монотонна.

2) последовательность ограничена сверху, если $\exists M \in \mathbb{R}:\forall n \in \mathbb{N}:a_n<M$. последовательность $\{a_n\}$ не ограничена сверху

последовательность ограничена снизу, если $\exists m \in \mathbb{R}:\forall n \in \mathbb{N}:a_n>m$. последовательность $\{a_n\}$ограничена снизу, $m=1$

3) $a_5 = 2^5-5=32-5=27$

$\{b_n\}_{n=2}^\infty=\frac{1}{1-n}$

1) последовательность монотонная, если знак разности между предыдущем и текущем ее членом не меняется.
$b_n - b_{n-1}=\frac{1}{1-n}-\frac{1}{1-n+1}= $ - это функция положительна для всех $n>=2$, значит исходная последовательность монотонна.

2) последовательность ограничена сверху, если $\exists M \in \mathbb{R}:\forall n \in \mathbb{N}:b_n<M$. последовательность $\{b_n\}$ не ограничена сверху

последовательность ограничена снизу, если $\exists m \in \mathbb{R}:\forall n \in \mathbb{N}:b_n>m$. последовательность $\{b_n\}$ограничена снизу, $m=-1$
 

3) $b_5 = \frac{1}{1-5}=-\frac{1}{4}$

$\{c_n\}_{n=1}^\infty=-1^n+\sqrt{2n}$

1) последовательность монотонная, если знак разности между предыдущем и текущем ее членом не меняется.
$c_n - c_{n-1}=-1^n+\sqrt{2n}+1^{n-1}-\sqrt{2\cdot(n-1)}$ - это функция положительна для всех $n>=1$, значит исходная последовательность монотонна.

2) последовательность ограничена сверху, если $\exists M \in \mathbb{R}:\forall n \in \mathbb{N}:c_n<M$. последовательность $\{c_n\}$ не ограничена сверху

последовательность ограничена снизу, если $\exists m \in \mathbb{R}:\forall n \in \mathbb{N}:c_n>m$. последовательность $\{c_n\}$ограничена снизу, $m=-1+\sqrt{2}$
 

3) $c_5 = -1^5+\sqrt{2\cdot5}=-1+\sqrt{10}$

$\{d_n\}_{n=1}^\infty=(-1)^{2n}+\frac{1}{n^2}$

1) последовательность монотонная, если знак разности между предыдущем и текущем ее членом не меняется.
$d_n - d_{n-1}=(-1)^{2n}+\frac{1}{n^2}-(-1)^{2\cdot(n-1)}+\frac{1}{(n-1)^2}$ - это функция положительна для всех $n>=1$, значит исходная последовательность монотонна.

2) последовательность ограничена сверху, если $\exists M \in \mathbb{R}:\forall n \in \mathbb{N}:d_n<M$. последовательность $\{d_n\}$ не ограничена сверху

последовательность ограничена снизу, если $\exists m \in \mathbb{R}:\forall n \in \mathbb{N}:d_n>m$. последовательность $\{d_n\}$ограничена снизу, $m=2$


3) $d_5 = (-1)^{2\cdot5}+\frac{1}{5^2}=1.04$

### Задание 5
найти 12-й член неявно заданной последовательности:
$a_1 = 128, a_{n+1}-a_n=6$

найдем общую формулу для $a_n$:

$a_n=a_1+6\cdot (n-1)$

тогда $a_{12}=128+6\cdot 11=62$